\include "global.ily"
\include "drums_up-I.ily"
\include "drums_down-I.ily"
\include "drums_up-II.ily"
\include "drums_down-II.ily"
%% \include "drums_up-III.ily"
\include "drums_down-III.ily"
%% \include "drums_up-IV.ily"
\include "drums_down-IV.ily"
%% \include "drums_up-V.ily"
\include "drums_down-V.ily"
