#+OPTIONS: title:t toc:t date:nil author:t email:nil num:nil
#+TITLE: Halfway House
#+DATE: [2016-06-29 Wed]
#+AUTHOR: Eric Bailey
#+EMAIL: naptakerband@gmail.com
#+LANGUAGE: en
#+CREATOR: Emacs 25.0.94.1 (Org mode 8.3.4)

* Front Matter
:PROPERTIES:
:tangle:   include/global.ily
:END:
Every good LilyPond file starts with a ~\version~:
#+BEGIN_SRC LilyPond
\version "2.19.24"
#+END_SRC

Include some libraries and such:
#+BEGIN_SRC LilyPond
#(load "../../include/naptaker.scm")
\include "preamble.ily"
\include "instruments.ily"
\include "openlilylib"
\useLibrary gridly
#+END_SRC

Define some useful variables.
#+BEGIN_SRC LilyPond
Key    = { \key c \major }
Tempo  = { \tempo 4 = 220 }
global = { \Tempo \defaultTimeSignature \time 4/4 }
#+END_SRC

Then the ~\header~ metadata:
#+BEGIN_SRC LilyPond
\header {
  title     = "Halfway House"
  opus      = "Naptime"
  composer  = "Sam Albers"
  %% poet      = "Preston Y. Drum"
  arranger  = "Naptaker"
  copyright = "© 2016 Naptaker"
}
#+END_SRC
* Templates
:PROPERTIES:
:tangle:   include/global.ily
:END:
First, initialize a grid with nine segments and all the parts.
#+BEGIN_SRC LilyPond
\gridInit 2 #'("meta" "vox" "guitar" "bass" "drums up" "drums down")
#+END_SRC

Next, initialize the template with a list of the lengths (in measures)
of every segment.
#+BEGIN_SRC LilyPond
\templateInit #'(16 16)
#+END_SRC
* Segments
** I: Chordy Riff
*** Meta
#+BEGIN_SRC LilyPond :tangle include/global.ily
\gridPutMusic "meta" 1
{
  \global
  \mark 1
  s1*8 \break
  s1*8 \break
}
#+END_SRC
*** TODO Vocals
*** DONE Guitar
CLOSED: [2016-06-29 Wed 20:55]
#+BEGIN_SRC LilyPond :tangle parts/guitar-I.ily
\include "global.ily"
\include "notation-snippets/guitar-string-bending/definitions.ily"

\gridPutMusic "guitar" 1
\relative c {
  \repeat unfold 4 {
    \include "notes/guitar-I.ily"
  }
}

\gridCompileCell "guitar" 1
#+END_SRC

This segment is predomintantly strummed minor chords
with a little bend ornament on the A minor.
#+BEGIN_SRC LilyPond :tangle notes/guitar-I.ily
\repeat unfold 2 {
  \repeat percent 2 { <c g' c ees g c>4 8 } 4 |
}
\repeat percent 2 { <a e' a c e a>4 8 } 4 |
<<
  { d'8.\3 ( \shiftBend e16\3 ) s2. | }
  \\
  { <a,,\6 e'\5 a\4 e'\2 a\1>4 <a e' a d e a>8 <a e' a c e a>4 8 4 | }
>>
#+END_SRC
*** TODO Bass
*** TODO Drums

** II: Noodly Riff
*** Meta
#+BEGIN_SRC LilyPond :tangle include/global.ily
\gridPutMusic "meta" 2
{
  \mark 2
  \global
  s1*8 \break
  s1*8 \break
}
#+END_SRC
*** TODO Vocals
*** DONE Guitar
CLOSED: [2016-06-29 Wed 19:54]
#+BEGIN_SRC LilyPond :tangle parts/guitar-II.ily
\include "global.ily"

\gridPutMusic "guitar" 2
\relative fis, {
  \repeat unfold 3 {
    \include "notes/guitar-IIa.ily"
    \include "notes/guitar-IIb.ily"
  }
  \relative fis, {
    \include "notes/guitar-IIa.ily"
    \include "notes/guitar-IIc.ily"
  }
}

\gridCompileCell "guitar" 2
#+END_SRC

#+BEGIN_SRC LilyPond :tangle notes/guitar-IIa.ily
<fis cis' fis a cis fis>4 \repeat percent 2 { 8 4 } |
<g d' g b d g>4           \repeat percent 2 { 8 4 } |
#+END_SRC
#+BEGIN_SRC LilyPond :tangle notes/guitar-IIb.ily
\ottava #1
a'4.\4 e'\2 g4\2 |
fis4\2 dis\3 c\3 a\4 |
\ottava #0
#+END_SRC
#+BEGIN_SRC LilyPond :tangle notes/guitar-IIc.ily
\ottava #1
a'4.\4 ees'\3 e4\2 |
g4\2 a\1 \once \hideNotes \grace { c\glissando } ees\1 c\1 |
\ottava #0
#+END_SRC
*** TODO Bass
TODO: Confirm with Sam that this transcription is accurate (enough).
#+BEGIN_SRC LilyPond :tangle parts/bass-II.ily
\include "global.ily"

\gridPutMusic "bass" 2
\relative fis,, {
  \repeat unfold 3 {
    \include "notes/bass-IIa.ily"
    \include "notes/bass-IIb.ily"
  }
  \relative fis,, {
    \include "notes/bass-IIa.ily"
    \include "notes/bass-IIc.ily"
  }
}

\gridCompileCell "bass" 2
#+END_SRC

#+BEGIN_SRC LilyPond :tangle notes/bass-IIa.ily
fis4. cis' d4 |
g,4.  cis  d4 |
#+END_SRC
#+BEGIN_SRC LilyPond :tangle notes/bass-IIb.ily
a4.      e'   g4 |
fis4 dis    c a  |
#+END_SRC
#+BEGIN_SRC LilyPond :tangle notes/bass-IIc.ily
a4.   ees'      e4 |
g4  a      ees' c  |
#+END_SRC
*** TODO Drums
* Parts
** Guitar
#+BEGIN_SRC LilyPond :tangle parts/guitar.ily
\include "global.ily"
\include "guitar-I.ily"
\include "guitar-II.ily"
#+END_SRC
** Bass
#+BEGIN_SRC LilyPond :tangle parts/bass.ily
\include "global.ily"
%% \include "bass-I.ily"
\include "bass-II.ily"
#+END_SRC
* Main
:PROPERTIES:
:tangle:   main.ly
:END:
Include the grid, templates and header metadata ([[file:include/global.ily][global.ily]]), and the parts.
#+BEGIN_SRC LilyPond
\include "global.ily"
\include "parts/bass.ily"
\include "parts/guitar.ily"
#+END_SRC

Print out the grid while rendering and
ensure all segments are of appropriate length.
#+BEGIN_SRC LilyPond
\gridDisplay
\gridCheck
#+END_SRC

During the process of transcribing a score, it can be useful to render a
particular range of the grid. GridLy provides a function, ~gridSetRange~ to
do just that.

By default, all segments are retrieved:
#+BEGIN_SRC LilyPond :tangle no
\gridSetRange #'all
#+END_SRC

... but you can specify a dotted pair (start and end):
#+BEGIN_SRC LilyPond :tangle no
\gridSetRange #'(1 . 2)
#+END_SRC

... or a single segment index:
#+BEGIN_SRC LilyPond :tangle no
\gridSetRange 1
#+END_SRC

Configure the score to be printed, including some visual tweaks.
#+BEGIN_SRC LilyPond
openDminorTuning = \stringTuning  <d, a, d f a d'>

\score {
  \Naptaker \openDminorTuning

  \layout {
    %% Increase the size of bar numbers by 2
    \override Score.BarNumber.font-size = #2

    %% Draw a box around bar numbers
    \override Score.BarNumber.stencil =
    #(make-stencil-boxer 0.1 0.25 ly:text-interface::print)

    \override Score.BarNumber.padding = #3
  }
}
#+END_SRC

Configure the MIDI output.
#+BEGIN_SRC LilyPond
\score {
  \unfoldRepeats \Naptaker \openDminorTuning
  \midi { }
}
#+END_SRC
