name: "Build site"
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v8
    - name: Allow unfree
      run: |
        mkdir -p ~/.config/nixpkgs
        echo '{ allowUnfree = true; }' >~/.config/nixpkgs/config.nix
    - uses: cachix/cachix-action@v6
      with:
        name: yurrriq
        skipPush: true
    - name: Build
      run: nix-build -o docs
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v1.5.1
      if: success()
      with:
        target_branch: gh-pages
        build_dir: docs
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
